### ISSUE TITLE
New update error on stop while mining

### ISSUE THREAD

**Issue by AKiman87** [angelbbs/NiceHashMinerLegacy#146]
When I stop the mining proccess I recieve this error.

Unhandled exception has occured in your application. If you click Continue, th eapplication will ignore this error and attempt to continue. If you click Quit, the application will close immediately.

Fan is cuurently set to auto. Cannot set fan speed.

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
MSI.Afterburner.Exceptions.MACMFanControlNotManual: Fan is currently set to auto.  Cannot set fan speed.
   at MSI.Afterburner.ControlMemoryGpuEntry.set_FanSpeedCur(UInt32 value)
   at NiceHashMiner.Devices.MSIAfterburner.ResetToDefaults(Int32 _busID, Boolean commit, Boolean nocheck) in D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Devices\MSIAfterburner.cs:line 610
   at NiceHashMiner.Form_Main.StopMining() in D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Forms\Form_Main.cs:line 3025
   at NiceHashMiner.Form_Main.ButtonStopMining_Click(Object sender, EventArgs e) in D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Forms\Form_Main.cs:line 2340
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4420.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
NiceHashMinerLegacy
    Assembly Version: 1.0.8029.25231
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/****/AppData/Roaming/NHML%20Fork%20Fix/NiceHashMinerLegacy.exe
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4360.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4400.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
NiceHashMinerLegacy.Common
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/****/AppData/Roaming/NHML%20Fork%20Fix/NiceHashMinerLegacy.exe
----------------------------------------
System.Runtime
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.dll
----------------------------------------
websocket-sharp
    Assembly Version: 1.0.2.21356
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/****/AppData/Roaming/NHML%20Fork%20Fix/NiceHashMinerLegacy.exe
----------------------------------------
Newtonsoft.Json
    Assembly Version: 10.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/****/AppData/Roaming/NHML%20Fork%20Fix/NiceHashMinerLegacy.exe
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Management
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4435.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4250.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4270.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
log4net
    Assembly Version: 1.2.15.0
    Win32 Version: 1.2.15.0
    CodeBase: file:///C:/Users/****/AppData/Roaming/NHML%20Fork%20Fix/log4net.DLL
----------------------------------------
MessageBoxManager
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/****/AppData/Roaming/NHML%20Fork%20Fix/NiceHashMinerLegacy.exe
----------------------------------------
OpenHardwareMonitorLib
    Assembly Version: 0.9.6.0
    Win32 Version: 0.9.6.0
    CodeBase: file:///C:/Users/****/AppData/Roaming/NHML%20Fork%20Fix/OpenHardwareMonitorLib.DLL
----------------------------------------
NiceHashMinerLegacy.Extensions
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/****/AppData/Roaming/NHML%20Fork%20Fix/NiceHashMinerLegacy.exe
----------------------------------------
System.Collections
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Collections/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Collections.dll
----------------------------------------
System.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Linq/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Linq.dll
----------------------------------------
ManagedNvml
    Assembly Version: 8.0.22.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/****/AppData/Roaming/NHML%20Fork%20Fix/NiceHashMinerLegacy.exe
----------------------------------------
NiceHashMinerLegacy.UUID
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/****/AppData/Roaming/NHML%20Fork%20Fix/NiceHashMinerLegacy.exe
----------------------------------------
BouncyCastle.Crypto
    Assembly Version: 1.8.5.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/****/AppData/Roaming/NHML%20Fork%20Fix/NiceHashMinerLegacy.exe
----------------------------------------
PInvokeDelegateFactoryInternalAssembly
    Assembly Version: 0.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/****/AppData/Roaming/NHML%20Fork%20Fix/NiceHashMinerLegacy.exe
----------------------------------------
MSIAfterburner.NET
    Assembly Version: 1.1.1.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/****/AppData/Roaming/NHML%20Fork%20Fix/NiceHashMinerLegacy.exe
----------------------------------------
PInvokeDelegateFactoryInternalAssembly
    Assembly Version: 0.0.0.0
    Win32 Version: 0.9.6.0
    CodeBase: file:///C:/Users/****/AppData/Roaming/NHML%20Fork%20Fix/OpenHardwareMonitorLib.dll
----------------------------------------
Microsoft.CSharp
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
----------------------------------------
System.Dynamic
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Dynamic/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Dynamic.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.8.4420.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
NiceHashMinerLegacy.Divert
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/****/AppData/Roaming/NHML%20Fork%20Fix/NiceHashMinerLegacy.exe
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by angelbbs** [comment]
What configuration your mining rig? 
Temporary disable "reset to default" switch in overclock tab.

**Comment by angelbbs** [comment]
Unzip this https://github.com/angelbbs/NiceHashMinerLegacy/blob/master-old/LatestBuild/nhmlffLatest.zip file into program folder with owerwriting files.
Then send me result,, please

**Comment by AKiman87** [comment]
That fixed the issue on both rigs. Thanks for your help. I'm not sure what other results you may want.
