### ISSUE TITLE
Versions 44, 45 fail on launch (10% Querying CPU)

### ISSUE THREAD

**Issue by AlanBlayney** [angelbbs/NiceHashMinerLegacy#162]
For any version >43.3, launching program fails at 10%: Querying CPU devices
CPU: 8086k
Windows: 11

************** Exception Text **************
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at NiceHashMiner.Devices.ComputeDeviceManager.Query.WindowsDisplayAdapters.QueryVideoControllers(List`1 avaliableVideoControllers, Boolean warningsEnabled) in D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Devices\ComputeDeviceManager.cs:line 852
   at NiceHashMiner.Devices.ComputeDeviceManager.Query.WindowsDisplayAdapters.QueryVideoControllers() in D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Devices\ComputeDeviceManager.cs:line 649
   at NiceHashMiner.Devices.ComputeDeviceManager.Query.QueryDevices(IMessageNotifier messageNotifier) in D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Devices\ComputeDeviceManager.cs:line 384
   at NiceHashMiner.Form_Main.StartupTimer_Tick(Object sender, EventArgs e) in D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Forms\Form_Main.cs:line 718
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4470.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
NiceHashMinerLegacy
    Assembly Version: 1.0.8116.20796
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Alan/AppData/Roaming/NHML%20Fork%20Fix/NiceHashMinerLegacy.exe
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4488.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4488.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4395.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
NiceHashMinerLegacy.Common
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Alan/AppData/Roaming/NHML%20Fork%20Fix/NiceHashMinerLegacy.exe
----------------------------------------
System.Runtime
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4161.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.dll
----------------------------------------
websocket-sharp
    Assembly Version: 1.0.2.29245
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Alan/AppData/Roaming/NHML%20Fork%20Fix/NiceHashMinerLegacy.exe
----------------------------------------
Newtonsoft.Json
    Assembly Version: 10.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Alan/AppData/Roaming/NHML%20Fork%20Fix/NiceHashMinerLegacy.exe
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4341.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4470.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4161.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Management
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4435.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4161.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4455.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4455.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
log4net
    Assembly Version: 1.2.15.0
    Win32 Version: 1.2.15.0
    CodeBase: file:///C:/Users/Alan/AppData/Roaming/NHML%20Fork%20Fix/log4net.DLL
----------------------------------------
MessageBoxManager
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Alan/AppData/Roaming/NHML%20Fork%20Fix/NiceHashMinerLegacy.exe
----------------------------------------
OpenHardwareMonitorLib
    Assembly Version: 0.9.6.0
    Win32 Version: 0.9.6.0
    CodeBase: file:///C:/Users/Alan/AppData/Roaming/NHML%20Fork%20Fix/OpenHardwareMonitorLib.DLL
----------------------------------------
NiceHashMinerLegacy.Extensions
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Alan/AppData/Roaming/NHML%20Fork%20Fix/NiceHashMinerLegacy.exe
----------------------------------------
System.Collections
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4161.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Collections/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Collections.dll
----------------------------------------
System.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4161.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Linq/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Linq.dll
----------------------------------------
ManagedNvml
    Assembly Version: 8.0.22.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Alan/AppData/Roaming/NHML%20Fork%20Fix/NiceHashMinerLegacy.exe
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

LOG

[2022-03-23 15:24:20] [INFO] [NICEHASH] Starting up NiceHashMiner Legacy Fork Fix: Build date 03/22/2022 11:33:12
[2022-03-23 15:24:20] [INFO] [NICEHASH] Selected language: English
[2022-03-23 15:24:20] [INFO] [NICEHASH] Critical error: missing language
[2022-03-23 15:24:20] [INFO] [NICEHASH] WMI service seems to be running, ManagementObjectSearcher returned success.
[2022-03-23 15:24:20] [INFO] [NICEHASH] Start Form_Main
[2022-03-23 15:24:20] [INFO] [NICEHASH] Start InitializeComponent
[2022-03-23 15:24:21] [INFO] [NICEHASH] Start InitLocalization
[2022-03-23 15:24:21] [INFO] [SystemSpecs] FreePhysicalMemory = 15861288
[2022-03-23 15:24:21] [INFO] [SystemSpecs] FreeSpaceInPagingFiles = 7160144
[2022-03-23 15:24:21] [INFO] [SystemSpecs] FreeVirtualMemory = 7492756
[2022-03-23 15:24:21] [INFO] [SystemSpecs] LargeSystemCache = 0
[2022-03-23 15:24:21] [INFO] [SystemSpecs] MaxNumberOfProcesses = 4294967295
[2022-03-23 15:24:21] [INFO] [SystemSpecs] MaxProcessMemorySize = 137438953344
[2022-03-23 15:24:21] [INFO] [SystemSpecs] NumberOfLicensedUsers = 0
[2022-03-23 15:24:21] [INFO] [SystemSpecs] NumberOfProcesses = 289
[2022-03-23 15:24:21] [INFO] [SystemSpecs] NumberOfUsers = 2
[2022-03-23 15:24:21] [INFO] [SystemSpecs] OperatingSystemSKU = 48
[2022-03-23 15:24:21] [INFO] [SystemSpecs] SizeStoredInPagingFiles = 7249892
[2022-03-23 15:24:21] [INFO] [SystemSpecs] SuiteMask = 272
[2022-03-23 15:24:21] [INFO] [SystemSpecs] TotalSwapSpaceSize = 0
[2022-03-23 15:24:21] [INFO] [SystemSpecs] TotalVirtualMemorySize = 40677776
[2022-03-23 15:24:21] [INFO] [SystemSpecs] TotalVisibleMemorySize = 33427884
[2022-03-23 15:24:21] [INFO] [SystemSpecs] ProcessorCount = 12
[2022-03-23 15:24:21] [INFO] [NICEHASH] Windows version 10 (10.0 build: 22000)
[2022-03-23 15:24:21] [INFO] [NICEHASH] Start query RAM
[2022-03-23 15:24:21] [INFO] [NICEHASH] Total RAM: 32644MB
[2022-03-23 15:24:21] [INFO] [NICEHASH] Page File Size: 7080MB
[2022-03-23 15:24:21] [INFO] [Windows Defender] snoozed
[2022-03-23 15:24:21] [INFO] [ExtraLaunchParameters] Creating internal params config MinerOptionPackage_ccminer
[2022-03-23 15:24:21] [INFO] [ExtraLaunchParameters] Creating internal params config MinerOptionPackage_hsrneoscrypt
[2022-03-23 15:24:21] [INFO] [ExtraLaunchParameters] Creating internal params config MinerOptionPackage_CryptoDredge
[2022-03-23 15:24:21] [INFO] [ExtraLaunchParameters] Creating internal params config MinerOptionPackage_trex
[2022-03-23 15:24:21] [INFO] [ExtraLaunchParameters] Creating internal params config MinerOptionPackage_NBMiner
[2022-03-23 15:24:21] [INFO] [ExtraLaunchParameters] Creating internal params config MinerOptionPackage_miniZ
[2022-03-23 15:24:21] [INFO] [ExtraLaunchParameters] Creating internal params config MinerOptionPackage_Kawpowminer
[2022-03-23 15:24:21] [INFO] [ExtraLaunchParameters] Creating internal params config MinerOptionPackage_TTMiner
[2022-03-23 15:24:21] [INFO] [ExtraLaunchParameters] Creating internal params config MinerOptionPackage_ZEnemy
[2022-03-23 15:24:21] [INFO] [ExtraLaunchParameters] Creating internal params config MinerOptionPackage_ccminer_CryptoNight
[2022-03-23 15:24:21] [INFO] [ExtraLaunchParameters] Creating internal params config MinerOptionPackage_ethminer_OCL
[2022-03-23 15:24:21] [INFO] [ExtraLaunchParameters] Creating internal params config MinerOptionPackage_ethminer_CUDA
[2022-03-23 15:24:21] [INFO] [ExtraLaunchParameters] Creating internal params config MinerOptionPackage_mkxminer
[2022-03-23 15:24:21] [INFO] [ExtraLaunchParameters] Creating internal params config MinerOptionPackage_teamredminer
[2022-03-23 15:24:21] [INFO] [ExtraLaunchParameters] Creating internal params config MinerOptionPackage_lolMiner
[2022-03-23 15:24:21] [INFO] [ExtraLaunchParameters] Creating internal params config MinerOptionPackage_lolMinerBEAM
[2022-03-23 15:24:21] [INFO] [ExtraLaunchParameters] Creating internal params config MinerOptionPackage_cpuminer_opt
[2022-03-23 15:24:21] [INFO] [ExtraLaunchParameters] Creating internal params config MinerOptionPackage_nheqminer_CPU
[2022-03-23 15:24:21] [INFO] [ExtraLaunchParameters] Creating internal params config MinerOptionPackage_nheqminer_CUDA
[2022-03-23 15:24:21] [INFO] [ExtraLaunchParameters] Creating internal params config MinerOptionPackage_eqm_CUDA
[2022-03-23 15:24:21] [INFO] [ExtraLaunchParameters] Creating internal params config MinerOptionPackage_ClaymoreZcash
[2022-03-23 15:24:21] [INFO] [ExtraLaunchParameters] Creating internal params config MinerOptionPackage_ClaymoreNeoscrypt
[2022-03-23 15:24:21] [INFO] [ExtraLaunchParameters] Creating internal params config MinerOptionPackage_ClaymoreCryptoNight
[2022-03-23 15:24:21] [INFO] [ExtraLaunchParameters] Creating internal params config MinerOptionPackage_XmrigAMD
[2022-03-23 15:24:21] [INFO] [ExtraLaunchParameters] Creating internal params config MinerOptionPackage_XmrigNVIDIA
[2022-03-23 15:24:21] [INFO] [ExtraLaunchParameters] Creating internal params config MinerOptionPackage_WildRig
[2022-03-23 15:24:21] [INFO] [ExtraLaunchParameters] Creating internal params config MinerOptionPackage_SRBMiner
[2022-03-23 15:24:21] [INFO] [ExtraLaunchParameters] Creating internal params config MinerOptionPackage_OptiminerZcash
[2022-03-23 15:24:21] [INFO] [ExtraLaunchParameters] Creating internal params config MinerOptionPackage_excavator
[2022-03-23 15:24:21] [INFO] [ExtraLaunchParameters] Creating internal params config MinerOptionPackage_ClaymoreDual
[2022-03-23 15:24:21] [INFO] [ExtraLaunchParameters] Creating internal params config MinerOptionPackage_Phoenix
[2022-03-23 15:24:21] [INFO] [ExtraLaunchParameters] Creating internal params config MinerOptionPackage_EWBF
[2022-03-23 15:24:21] [INFO] [ExtraLaunchParameters] Creating internal params config MinerOptionPackage_Nanominer
[2022-03-23 15:24:21] [INFO] [ExtraLaunchParameters] Creating internal params config MinerOptionPackage_GMiner
[2022-03-23 15:24:21] [INFO] [ExtraLaunchParameters] Creating internal params config MinerOptionPackage_Bminer
[2022-03-23 15:24:21] [INFO] [ExtraLaunchParameters] Creating internal params config MinerOptionPackage_Xmrig
[2022-03-23 15:24:21] [INFO] [ExtraLaunchParameters] Creating internal params config MinerOptionPackage_CastXMR
[2022-03-23 15:24:21] [INFO] [ExtraLaunchParameters] Creating internal params config MinerOptionPackage_lyclMiner
[2022-03-23 15:24:21] [INFO] [ExtraLaunchParameters] Creating internal params config MinerOptionPackage_dstm
[2022-03-23 15:24:21] [INFO] [NICEHASH] Setting environment variables
[2022-03-23 15:24:23] [INFO] [Closing] 30576 NiceHashMinerLegacy

**Comment by angelbbs** [comment]
Please, send file logs\log.txt from program folder after program run

**Comment by AlanBlayney** [comment]
[log.txt](https://github.com/angelbbs/NiceHashMinerLegacy/files/8336816/log.txt)

**Comment by angelbbs** [comment]
Replace program file with this https://disk.yandex.ru/d/eTXtrLitmQnEag file and run again. Then send me logs, please

**Comment by AlanBlayney** [comment]
The program launched with the new exe, but crashed while trying to update the miners (which I had downloaded and extracted between installing and launching the program)
![image](https://user-images.githubusercontent.com/22134640/159832382-23a4ddee-d784-454a-aa44-65f5077deff0.png)
(full text below)

I then launched again and seemed to be able to benchmark and mine without trouble.
[log.txt](https://github.com/angelbbs/NiceHashMinerLegacy/files/8338061/log.txt)



See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at NiceHashMiner.Forms.Form_Downloading.client_EmergencyDownloadFileCompleted(Object sender, AsyncCompletedEventArgs e) in D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Forms\Form_Downloading.cs:line 87
   at NiceHashMiner.Updater.Updater.<>c__DisplayClass3_2.<EmergencyDownloader>b__0(Object sender, AsyncCompletedEventArgs args) in D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Updater\Updater.cs:line 139
   at System.ComponentModel.AsyncCompletedEventHandler.Invoke(Object sender, AsyncCompletedEventArgs e)
   at System.Net.WebClient.OnDownloadFileCompleted(AsyncCompletedEventArgs e)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4470.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
NiceHashMinerLegacy
    Assembly Version: 1.0.8118.1310
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files/NHML%20Fork%20Fix/NiceHashMinerLegacy.exe
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4488.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4488.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4395.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
NiceHashMinerLegacy.Common
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files/NHML%20Fork%20Fix/NiceHashMinerLegacy.exe
----------------------------------------
System.Runtime
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4161.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.dll
----------------------------------------
websocket-sharp
    Assembly Version: 1.0.2.29245
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files/NHML%20Fork%20Fix/NiceHashMinerLegacy.exe
----------------------------------------
Newtonsoft.Json
    Assembly Version: 10.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files/NHML%20Fork%20Fix/NiceHashMinerLegacy.exe
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4341.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4470.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4161.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Management
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4435.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4161.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4455.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4455.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
log4net
    Assembly Version: 1.2.15.0
    Win32 Version: 1.2.15.0
    CodeBase: file:///C:/Program%20Files/NHML%20Fork%20Fix/log4net.DLL
----------------------------------------
MessageBoxManager
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files/NHML%20Fork%20Fix/NiceHashMinerLegacy.exe
----------------------------------------
OpenHardwareMonitorLib
    Assembly Version: 0.9.6.0
    Win32 Version: 0.9.6.0
    CodeBase: file:///C:/Program%20Files/NHML%20Fork%20Fix/OpenHardwareMonitorLib.DLL
----------------------------------------
NiceHashMinerLegacy.Extensions
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files/NHML%20Fork%20Fix/NiceHashMinerLegacy.exe
----------------------------------------
System.Collections
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4161.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Collections/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Collections.dll
----------------------------------------
System.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4161.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Linq/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Linq.dll
----------------------------------------
ManagedNvml
    Assembly Version: 8.0.22.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files/NHML%20Fork%20Fix/NiceHashMinerLegacy.exe
----------------------------------------
NiceHashMinerLegacy.UUID
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files/NHML%20Fork%20Fix/NiceHashMinerLegacy.exe
----------------------------------------
BouncyCastle.Crypto
    Assembly Version: 1.8.5.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files/NHML%20Fork%20Fix/NiceHashMinerLegacy.exe
----------------------------------------
PInvokeDelegateFactoryInternalAssembly
    Assembly Version: 0.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files/NHML%20Fork%20Fix/NiceHashMinerLegacy.exe
----------------------------------------
PInvokeDelegateFactoryInternalAssembly
    Assembly Version: 0.0.0.0
    Win32 Version: 0.9.6.0
    CodeBase: file:///C:/Program%20Files/NHML%20Fork%20Fix/OpenHardwareMonitorLib.dll
----------------------------------------
Microsoft.CSharp
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4161.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
----------------------------------------
System.Dynamic
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4161.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Dynamic/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Dynamic.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.8.4470.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
NiceHashMinerLegacy.Divert
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files/NHML%20Fork%20Fix/NiceHashMinerLegacy.exe
----------------------------------------
SharpCompress
    Assembly Version: 0.10.3.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files/NHML%20Fork%20Fix/NiceHashMinerLegacy.exe
----------------------------------------
LinqBridge
    Assembly Version: 1.3.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files/NHML%20Fork%20Fix/NiceHashMinerLegacy.exe
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by angelbbs** [comment]
Thanks.
Please download https://disk.yandex.ru/d/eTXtrLitmQnEag and run again.

**Comment by AlanBlayney** [comment]
Launched program and began mining without any problems.
[log.txt](https://github.com/angelbbs/NiceHashMinerLegacy/files/8343058/log.txt)
