### ISSUE TITLE
ver 26 win32 exception

### ISSUE THREAD

**Issue by marlyn088** [angelbbs/NiceHashMinerLegacy#92]
Hi, 
installing ver 26 on windows 7 64 bit with SP1 ( i do have more then 4 computers and all have the same error.)
just updated my dotnet to 4.8 just updated my jave to 8 (the one listed on the 7 APR 2020)  FF ver 25 ran only with the gminer error of restarting aging for 2 times then it starts mining. so ver 25 no real problem
keep getting this error. 

************** Exception Text **************
System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at NiceHashMiner.Helpers.InstallVcRedist() in D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Utils\Helpers.cs:line 352
   at NiceHashMiner.Form_Main.StartupTimer_Tick(Object sender, EventArgs e) in D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Forms\Form_Main.cs:line 631
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by marlyn088** [comment]
ver 26 beta 2 had no problems installing and beched marked the 3 algorithms. so i think it worked with my nvidia's
